export const ADD_PRODUCT = 'ADD_PRODUCT'
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR'

export const START_PRODUCTS_DOWNLOAD = 'START_PRODUCTS_DOWNLOAD'
export const PRODUCTS_DOWNLOAD_SUCCESS = 'PRODUCTS_DOWNLOAD_SUCCESS'
export const PRODUCTS_DOWNLOAD_ERROR = 'PRODUCTS_DOWNLOAD_ERROR'

export const REMOVE_PRODUCT = 'REMOVE_PRODUCT'
export const REMOVE_PRODUCT_SUCCESS = 'REMOVE_PRODUCT_SUCCESS'
export const REMOVE_PRODUCT_ERROR = 'REMOVE_PRODUCT_ERROR'

export const GET_EDIT_PRODUCT = 'GET_EDIT_PRODUCT'
export const EDIT_PRODUCT = 'EDIT_PRODUCT'
export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS'
export const EDIT_PRODUCT_ERROR = 'EDIT_PRODUCT_ERROR'
